name: AshtonsEssentials
version: '${project.version}'
main: me.ashton.developer.ashtonsessentials.AshtonsEssentials
api-version: 1.17
author: AshtonThyPorgrammer
description: AshtonsEssentials is a minecraft plugin just like essentials but with more commands and features. Futher more AshtonsEssentials will be updated weekly with new features and commands.
website: https://github.com/AshtonFM
commands:
  setspawn:
    description: Sets the spawn point of the server.
    usage: /<command>
    aliases:
      - sp
      - sspawn
  spawn:
    description: Teleports the player to the cords set using /setspawn
    usage: /<command>
